### ISSUE TITLE
Initial Run error

### ISSUE THREAD

**Issue by jonnilundy** [Robert-Frampton/generator-metal-ssg#1]
jonnilundy ~ $ yo metal-ssg

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the splendid │
   `---------´   │   Metal SSG generator!   │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What would you like to call your project? senna.js
? Would you like to use this as the project id? (determines folder name) y

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-metal-ssg/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-metal-ssg/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-metal-ssg/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at child.app (/usr/local/lib/node_modules/generator-metal-ssg/generators/app/index.js:37:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-metal-ssg/node_modules/yeoman-generator/lib/base.js:439:23)
    at /usr/local/lib/node_modules/generator-metal-ssg/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-metal-ssg/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-metal-ssg/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by Robert-Frampton** [comment]
@jonnilundy can you still reproduce this?

**Comment by Robert-Frampton** [comment]
Closing this, pretty sure this issue has been addressed already.
